version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: kisia_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kisia_hotel
      MYSQL_USER: kisia
      MYSQL_PASSWORD: kisia
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-time-zone='+09:00'

  web:
    build: .
    container_name: kisia_web
    ports:
      - "8080:80"     # HTTP
      - "8443:443"    # HTTPS
    volumes:
      - ./src:/var/www/html
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data: