version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: kisia_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kisia_hotel
      MYSQL_USER: kisia
      MYSQL_PASSWORD: kisia
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: always

  web:
    build: .
    container_name: kisia_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data: 
